### PR TITLE
Add schema for old signatures

### PR DESCRIPTION
**Pull request by tiltingpenguin**
This PR aims to add a schema for the old distro_signatures we still support in cobbler and also fix some issues in the schema like required values not being enforced

Fixes https://github.com/cobbler/libcobblersignatures/issues/63

### CODE REVIEW

**Comment by SchoolGuy** [comment]
This PR will get a review from me however, @tiltingpenguin will also state his opinion about my changes. I will work on this PR this evening and he will take it back over tomorrow.

**Comment by SchoolGuy** [comment]
The failing validations need to be now compared to the main repository and we need to decide what schema we would like to use in the end and what errors need to be fixed where. The schema MUST validate without errors against shipped versions of Cobbler.

**Comment by tiltingpenguin** [comment]
The validation error in the latest signatures comes from a typo in the signatures in cobbler.github.io which will be fixed by https://github.com/cobbler/cobbler.github.io/pull/179

**Comment by SchoolGuy** [comment]
@tiltingpenguin Could you please double-check check the changes I did to the mentioned PR yesterday? If that is done I would merge that one and then rerun the actions here.

**Review by SchoolGuy — APPROVED** [review]
Let's rerun the CI once the linked PR (https://github.com/cobbler/cobbler.github.io/pull/179) is merged. After the CI is green we can merge this PR.

**Pull request merged**
